#pragma once

#include <QDialog>
#include <QInputDialog>
#include <QMessageBox>
#include "ui_CategorySelectionView.h"
#include "Model/Category.h"

/**
 * @brief Dialog for selecting, adding, and deleting categories
 * This dialog allows users to manage transaction categories through
 * selection, addition, and deletion operations.
 */
class CategorySelectionView : public QDialog
{
	Q_OBJECT

public:
	explicit CategorySelectionView(QWidget *parent = nullptr);
	~CategorySelectionView();

    /**
     * @brief Populates the dialog with existing categories
     * @param categories Vector of Category objects to display
     */
    void setCategories(const QVector<Category>& categories);

    /**
     * @brief Controls visibility of the category selection button
     * @param visible True to show, false to hide
     */
    void setSelectCategoryButtonVisible(bool visible);

    /**
     * @brief Gets the currently selected category ID
     * @return int Selected category ID or -1 if none selected
     */
    int getSelectedCategoryId() const { return selectedCategoryId; }
signals:
    /**
     * @brief Emitted when a category is selected
     * @param categoryId ID of the selected category
     */
    void selectRequestedCategory(int categoryId);

    /**
     * @brief Emitted when a new category is requested
     * @param categoryName Name of the category to add
     */
    void addRequestedCategory(const QString& categoryName);

    /**
     * @brief Emitted when a category deletion is requested
     * @param categoryId ID of the category to delete
     */
    void deleteRequestedCategory(int categoryId);

    //void editRequestedCategory(int categoryId); we will add this method later

private slots:
    void selectCategoryButtonClicked();
    void addCategoryButtonClicked();
    void deleteCategoryButtonClicked();
    void cancelButtonClicked();

    //void editCategoryButtonClicked();

private:
	Ui::CategorySelectionView* ui;      ///< Pointer to UI elements generated by Qt
    QVector<Category> categoryId;       ///< Local copy of categories for display
    int selectedCategoryId = -1;        ///< ID of currently selected category

    /**
     * @brief Connects UI buttons to their respective slot methods
     */
    void connectMethodToButton();
};

